### PR TITLE
fix scm tags in relased poms

### PR DESCRIPTION
**Pull request by Scyks**
I hope this is the way to fix wrong repository references. Would be glad if you can merge this.

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
pretty close ;-)

the correct place is https://github.com/scalacenter/scaladex-data/blob/master/claims.json

and this is what you need to add:

"com.github.scyks playacl_2.11 *": "scyks/play-acl"

I will do it for you and merge https://github.com/scalacenter/scaladex-metadata/pull/9/files

**Comment by MasseGuillaume** [comment]
https://github.com/scalacenter/scaladex-data/commit/50250e6fb42020af6d4d1a1fec718e0d3e91885e

**Comment by Scyks** [comment]
Thanks :)

**Comment by heathermiller** [comment]
Good guess @Scyks! Sorry that we hadn't made it clearer what one should do to fix these things. I think @MasseGuillaume recently added some pointers to the scaladex README, hopefully that helps some!

**Pull request closed without merging**
